language: python
python: 2.7
cache: pip

install:
  - pip install tox flake8

notifications:
  email:
    on_success: change
    on_failure: change

script:
  - tox
  - flake8 --select=F821,F823 . --exclude=.svn,CVS,.bzr,.hg,.git,__pycache__,.tox,.virtualenv,ext
